name: build

on:
  push:
    branches:
      - 'main'
env:
  PROJECT_NAME: 'stupid-public'

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set docker tag
        id: docker-tag
        run: |
          if ${{ github.ref == 'refs/heads/main' }}
          then
            echo "::set-output name=TAG::latest"
          else
            echo "::set-output name=TAG::${{ github.ref_name }}"
          fi

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            "marcelowa/${{ env.PROJECT_NAME }}:${{ steps.docker-tag.outputs.TAG }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max